/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class XwordBuilderTest {
    @Test
    public void testSomeLibraryMethod() throws IOException {
        Path path = Paths.get("/Users/sszuflita/Downloads/XwiWordList.txt");
        CrosswordBuilder builder = CrosswordBuilder.fromPath(path);

        Tile[][] base = new Tile[][]{
                new Tile[]{ Tile.EMPTY, Tile.EMPTY, Tile.EMPTY},
                new Tile[]{ Tile.EMPTY, Tile.EMPTY, Tile.EMPTY},
                new Tile[]{ Tile.EMPTY, Tile.EMPTY, Tile.EMPTY}
        };

        builder.solveFromGrid(new Crossword(base));
    }
}
