/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.google.common.base.Stopwatch;
import org.junit.Assert;
import org.junit.Test;
import xwords.Crossword;
import xwords.CrosswordBuilder;
import xwords.ParseUtils;
import xwords.Tile;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Set;
import java.util.concurrent.TimeUnit;

public class XwordBuilderTest {
    @Test
    public void testEmptyGrid() throws IOException {
        Path path = Paths.get("/Users/sszuflita/Downloads/XwiWordList.txt");
        CrosswordBuilder builder = CrosswordBuilder.fromPath(path);

        Tile[][] base = new Tile[][]{
                new Tile[]{ Tile.EMPTY, Tile.EMPTY, Tile.EMPTY},
                new Tile[]{ Tile.EMPTY, Tile.EMPTY, Tile.EMPTY},
                new Tile[]{ Tile.EMPTY, Tile.EMPTY, Tile.EMPTY}
        };

        Set<Crossword> crosswords = builder.solveFromGrid(new Crossword(base));

        Assert.assertTrue(crosswords.size() > 0);
    }

    @Test
    public void testNonEmptyGrid() throws IOException {
        Path path = Paths.get("/Users/sszuflita/Downloads/XwiWordList.txt");
        CrosswordBuilder builder = CrosswordBuilder.fromPath(path);

        Tile[][] base = new Tile[][]{
                new Tile[]{ Tile.A, Tile.EMPTY, Tile.EMPTY},
                new Tile[]{ Tile.EMPTY, Tile.EMPTY, Tile.EMPTY},
                new Tile[]{ Tile.EMPTY, Tile.EMPTY, Tile.EMPTY}
        };

      Set<Crossword> crosswords = builder.solveFromGrid(new Crossword(base));

      Assert.assertTrue(crosswords.size() > 0);
    }

    @Test
    public void testNonEmptyGridWithB() throws IOException {
        Path path = Paths.get("/Users/sszuflita/Downloads/XwiWordList.txt");
        CrosswordBuilder builder = CrosswordBuilder.fromPath(path);

        Tile[][] base = new Tile[][]{
                new Tile[]{ Tile.B, Tile.EMPTY, Tile.EMPTY},
                new Tile[]{ Tile.EMPTY, Tile.EMPTY, Tile.EMPTY},
                new Tile[]{ Tile.R, Tile.EMPTY, Tile.EMPTY}
        };

        Set<Crossword> crosswords = builder.solveFromGrid(new Crossword(base));

        Assert.assertTrue(crosswords.size() > 0);
    }

    @Test
    public void testInterestingGrid() throws IOException {
        Path path = Paths.get("/Users/sszuflita/Downloads/XwiWordList.txt");

        CrosswordBuilder builder = CrosswordBuilder.fromPath(path);

        Tile[][] tiles = ParseUtils.fromPath(Paths.get("src/test/resources/test.txt"));

        int num_trials = 1;
        long total_time = 0L;
        for (int i = 0; i < num_trials; i++) {
            Stopwatch started = Stopwatch.createStarted();
            Set<Crossword> crosswords = builder.solveFromGrid(new Crossword(tiles));
            started.stop();
            total_time += started.elapsed(TimeUnit.MILLISECONDS);
            System.out.println(crosswords.iterator().next());
        }
        System.out.println(total_time / num_trials);
    }
}
